# Generated by Django 4.0.2 on 2022-07-27 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(db_column='c_name', max_length=30)),
                ('company_regid', models.CharField(db_column='reg_id', max_length=12)),
                ('cmp_addr', models.CharField(db_column='addr', max_length=70)),
                ('country', models.CharField(db_column='cntry', max_length=30)),
                ('cmp_phno', models.CharField(db_column='phno', max_length=12)),
                ('acc_holder', models.CharField(db_column='acc_hld', max_length=30)),
                ('acc_no', models.CharField(db_column='acc_no', max_length=30)),
                ('acc_ifsc', models.CharField(db_column='ifsc', max_length=30)),
                ('user_type', models.CharField(db_column='type', max_length=20)),
                ('email', models.CharField(db_column='email', max_length=30)),
                ('passwd', models.CharField(db_column='passwd', max_length=30)),
                ('user_id', models.IntegerField(db_column='log_id')),
                ('request_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='inactive', max_length=20)),
            ],
            options={
                'db_table': 'resellers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=30)),
                ('reg_product_id', models.CharField(db_column='p_id', max_length=12)),
                ('desc', models.TextField(db_column='desc')),
                ('img', models.ImageField(blank=True, db_column='img', null=True, upload_to='product_images/')),
                ('price', models.IntegerField(db_column='price')),
                ('quantity', models.IntegerField(db_column='qty')),
                ('weight', models.IntegerField(db_column='wt')),
                ('weight_unit', models.CharField(db_column='unit', max_length=12)),
                ('category', models.CharField(db_column='cat', max_length=12)),
                ('subcategory', models.CharField(db_column='sub_cat', max_length=12)),
                ('vendor', models.CharField(db_column='vendor', max_length=100)),
                ('status', models.CharField(db_column='status', max_length=100)),
                ('reseller', models.ForeignKey(db_column='reseller', on_delete=django.db.models.deletion.CASCADE, to='reseller.resellers')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
